### ISSUE TITLE
Issues in Readme

### ISSUE THREAD

**Issue by MalinAhlberg** [CSCfi/elixir-rems-proxy#20]
#### Describe the bug
Hello!

I noticed some non-working instructions in the readme, when following the quick start guide.

#### To Reproduce
1. Set up the prerequisites, as described, then follow the steps in 'run without installing'. 
`python3 -m api.app` does not work (but `python3 -m elixir_rems_proxy.app` does :) )

2. Using the API, as described, does not work if you do not give a `elixir-api-key`, that will give you `Missing mandatory headers: 'elixir-api-key'`

3. Send the POST request gives `Following datasets are missing from REMS ([['example-org', 'urn:example-dataset-1'], ['example-org', 'urn:example-dataset-2']]), check "GET /user" endpoint for added permissions`

4. The added user does not show up when calling the `GET /user/username`: `Permissions for this user not found`

**Comment by teemukataja** [comment]
Hi,

The `README.md` covers the old version https://github.com/CSCfi/elixir-rems-proxy/tree/alpha.
The current version does not have any up-to-date docs, because it has been a proof-of-concept.
The docs will be re-written after the code has updated (estimated during this autumn).

Sorry for the inconvenience :(
