### ISSUE TITLE
Path to jwk key files not read from config.ini

### ISSUE THREAD

**Issue by MalinAhlberg** [CSCfi/elixir-rems-proxy#27]
#### Describe the bug
The path of the jwk key files can be set in the `config.ini` file. However, in when [parsing the configuration](https://github.com/CSCfi/elixir-rems-proxy/blob/8770844c6f93903532524b394a892fe19059b2fe/elixir_rems_proxy/config/__init__.py#L39), only the values from the os environment variables are looked at.
Also, the [key generation script](https://github.com/CSCfi/elixir-rems-proxy/blob/8770844c6f93903532524b394a892fe19059b2fe/elixir_rems_proxy/config/jwks.py#L26) always writes the files to the config dir (maybe intended?).

**Comment by teemukataja** [comment]
Ah, good find, it should indeed look for the path from the `config.ini` if the path is not set in environment variables. And then default to the config directory.

Yes, I set the file writing to be in the config directory, I thought this was useful for quick setups and testing/developing, that the keys are created and looked for in some default directory. For example, if you build the image and run it, it will hang because it's trying to load the key files, but they don't exist, but then if you execute `docker exec <container> python elixir_rems_proxy/config/jwks.py` for the container, it creates the keys inside the running container, and the web app picks up the files on next loop.

**Comment by MalinAhlberg** [comment]
Nice, thanks :)
